### ISSUE TITLE
使用扩展后，基岩版无法进入服务器

### ISSUE THREAD

**Issue by HaiXi2912** [zimzaza4/GeyserClickableMessageGUI#2]
服务器类型BC,扩展已安装到BC的Geyser中
Geyser版本：2.1.0
BC版本：waterfall-1.19-510
子服核心：Purpur-1.19.2-1769

报错内容：
基岩版客户端[Win10]:
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component com.github.steveice10.mc.protocol.packet.ingame.clientbound.ClientboundSystemChatPacket.getContent()

后台报错：
[03:55:38 INFO] [Geyser-BungeeCord]: 玩家以 SWHaiFeng 的用户名建立了连接
[03:55:38 INFO] [Geyser-BungeeCord]: SWHaiFeng (登录为: SWHaiFeng) 已连接到 Java 服务器
[03:55:39 WARN] [Geyser-BungeeCord]: Error whilst checking for Geyser update!
java.net.SocketTimeoutException: Connect timed out
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:539) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:666) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:378) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1661) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at org.geysermc.geyser.util.WebUtils.getJson(WebUtils.java:78) ~[?:?]
        at org.geysermc.geyser.util.VersionCheckUtils.lambda$checkForGeyserUpdate$0(VersionCheckUtils.java:60) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
[03:55:39 INFO] [Geyser-BungeeCord]: [GeyserClickableMessageGUI] add listener

...

[03:55:45 INFO] [Geyser-BungeeCord]: SWHaiFeng 因为 java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component com.github.steveice10.mc.protocol.packet.ingame.clientbound.ClientboundSystemChatPacket.getContent()' 与 Java 服务器断开了连接
[03:55:45 ERROR]: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.Component com.github.steveice10.mc.protocol.packet.ingame.clientbound.ClientboundSystemChatPacket.getContent()'
[03:55:45 ERROR]:       at re.imc.geyserclickablemessagegui.listener.ChatPacketSessionListener.packetReceived(ChatPacketSessionListener.java:21)
[03:55:45 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:156)
[03:55:45 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:377)
[03:55:45 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:28)
[03:55:45 ERROR]:       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:55:45 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:55:45 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[03:55:45 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:55:45 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:55:45 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[03:55:45 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:55:45 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:55:45 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[03:55:45 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:55:45 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482)
[03:55:45 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463)
[03:55:45 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[03:55:45 ERROR]:       at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[03:55:45 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[03:55:45 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[03:55:45 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[03:55:45 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:55:45 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[03:55:45 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by zimzaza4** [comment]
https://github.com/zimzaza4/GeyserClickableMessageGUI/releases/download/1.0.0/GeyserClickableMessageGUI-BC.jar
